# ===========================================
# ORION PROGRAM SERVICE - Configuration
# ===========================================

server:
  port: ${SERVER_PORT:8093}

spring:
  application:
    name: ${SERVICE_NAME:orion-program}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/oriondb}

  # Docker Compose (disabled by default)
  docker:
    compose:
      enabled: false

# External Services Configuration
orion:
  services:
    user-service-url: ${USER_SERVICE_URL:http://localhost:8092/service/user}
    connection-timeout: ${SERVICE_CONNECTION_TIMEOUT:5s}
    read-timeout: ${SERVICE_READ_TIMEOUT:10s}
    max-retries: ${SERVICE_MAX_RETRIES:3}
    retry-delay: ${SERVICE_RETRY_DELAY:500ms}
    failure-rate-threshold: ${SERVICE_FAILURE_RATE:50.0}
    minimum-number-of-calls: ${SERVICE_MIN_CALLS:5}
    wait-duration-in-open-state: ${SERVICE_CIRCUIT_WAIT:30s}

# Logging Configuration
logging:
  level:
    com.unibague.gradework: ${LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.springframework.data.mongodb: ${MONGODB_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# ===========================================
# DEVELOPMENT PROFILE
# ===========================================
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.unibague.gradework: DEBUG

---
# ===========================================
# DOCKER PROFILE
# ===========================================
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      uri: mongodb://mongo:27017/oriondb

# Docker network service discovery
orion:
  services:
    user-service-url: http://orion-user:8092/service/user

logging:
  level:
    com.unibague.gradework: INFO

---
# ===========================================
# PRODUCTION PROFILE
# ===========================================
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_PROD_URI}

# Production service URLs (externalized)
orion:
  services:
    user-service-url: ${USER_SERVICE_PROD_URL}
    connection-timeout: 3s
    read-timeout: 15s

logging:
  level:
    com.unibague.gradework: INFO
    root: WARN